default: &default
  port: 5432
  encoding: unicode
  adapter: postgresql
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'blog_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'blog_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'blog_production' %>